# Generated by Django 5.2.6 on 2025-09-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(verbose_name="Описание номера")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Цена за ночь")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата добавления")),
            ],
            options={
                "verbose_name": "Номер",
                "verbose_name_plural": "Номера",
                "ordering": ["-created_at"],
            },
        ),
    ]
