# Generated by Django 5.2.6 on 2025-09-21 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_start", models.DateField(verbose_name="Дата заезда")),
                ("date_end", models.DateField(verbose_name="Дата выезда")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания брони")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="rooms.room",
                        verbose_name="Номер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронь",
                "verbose_name_plural": "Брони",
                "ordering": ["date_start"],
            },
        ),
    ]
